<?xml version='1.0' encoding='utf-8'?>
<tileset name="Rooftops" tilewidth="16" tileheight="16" tilecount="256" columns="16"><image source="Images/Set_F_Rooftops.png" trans="ff01fe" width="256" height="256" /><terraintypes> 
  <terrain name="Roof1" tile="0" />
  <terrain name="Roof2" tile="5" />
  <terrain name="Roof3" tile="8" />
  <terrain name="Roof4" tile="13" />
  <terrain name="Roof5" tile="128" />
  <terrain name="Roof6" tile="133" />
  <terrain name="Roof7" tile="136" />
  </terraintypes><tile id="0" terrain="0,,," />
  <tile id="1" terrain=",,,," />
  <tile id="2" terrain=",,,," />
  <tile id="3" terrain=",,,," />
  <tile id="4" terrain=",,,," />
  <tile id="5" terrain=",1,," />
  <tile id="6" terrain=",,,," />
  <tile id="7" terrain=",,,," />
  <tile id="8" terrain=",,2," />
  <tile id="9" terrain=",,,," />
  <tile id="10" terrain=",,,," />
  <tile id="11" terrain=",,,," />
  <tile id="12" terrain=",,,," />
  <tile id="13" terrain=",,,3" />
  <tile id="14" terrain=",,,," />
  <tile id="15" terrain=",,,," />
  <tile id="16" terrain=",,,," />
  <tile id="17" terrain=",,,," />
  <tile id="18" terrain=",,,," />
  <tile id="19" terrain=",,,," />
  <tile id="20" terrain=",,,," />
  <tile id="21" terrain=",,,," />
  <tile id="22" terrain=",,,," />
  <tile id="23" terrain=",,,," />
  <tile id="24" terrain=",,,," />
  <tile id="25" terrain=",,,," />
  <tile id="26" terrain=",,,," />
  <tile id="27" terrain=",,,," />
  <tile id="28" terrain=",,,," />
  <tile id="29" terrain=",,,," />
  <tile id="30" terrain=",,,," />
  <tile id="31" terrain=",,,," />
  <tile id="32" terrain=",,,," />
  <tile id="33" terrain=",,,," />
  <tile id="34" terrain=",,,," />
  <tile id="35" terrain=",,,," />
  <tile id="36" terrain=",,,," />
  <tile id="37" terrain=",,,," />
  <tile id="38" terrain=",,,," />
  <tile id="39" terrain=",,,," />
  <tile id="40" terrain=",,,," />
  <tile id="41" terrain=",,,," />
  <tile id="42" terrain=",,,," />
  <tile id="43" terrain=",,,," />
  <tile id="44" terrain=",,,," />
  <tile id="45" terrain=",,,," />
  <tile id="46" terrain=",,,," />
  <tile id="47" terrain=",,,," />
  <tile id="48" terrain=",,,," />
  <tile id="49" terrain=",,,," />
  <tile id="50" terrain=",,,," />
  <tile id="51" terrain=",,,," />
  <tile id="52" terrain=",,,," />
  <tile id="53" terrain=",,,," />
  <tile id="54" terrain=",,,," />
  <tile id="55" terrain=",,,," />
  <tile id="56" terrain=",,,," />
  <tile id="57" terrain=",,,," />
  <tile id="58" terrain=",,,," />
  <tile id="59" terrain=",,,," />
  <tile id="60" terrain=",,,," />
  <tile id="61" terrain=",,,," />
  <tile id="62" terrain=",,,," />
  <tile id="63" terrain=",,,," />
  <tile id="64" terrain=",,,," />
  <tile id="65" terrain=",,,," />
  <tile id="66" terrain=",,,," />
  <tile id="67" terrain=",,,," />
  <tile id="68" terrain=",,,," />
  <tile id="69" terrain=",,,," />
  <tile id="70" terrain=",,,," />
  <tile id="71" terrain=",,,," />
  <tile id="72" terrain=",,,," />
  <tile id="73" terrain=",,,," />
  <tile id="74" terrain=",,,," />
  <tile id="75" terrain=",,,," />
  <tile id="76" terrain=",,,," />
  <tile id="77" terrain=",,,," />
  <tile id="78" terrain=",,,," />
  <tile id="79" terrain=",,,," />
  <tile id="80" terrain=",,,," />
  <tile id="81" terrain=",,,," />
  <tile id="82" terrain=",,,," />
  <tile id="83" terrain=",,,," />
  <tile id="84" terrain=",,,," />
  <tile id="85" terrain=",,,," />
  <tile id="86" terrain=",,,," />
  <tile id="87" terrain=",,,," />
  <tile id="88" terrain=",,,," />
  <tile id="89" terrain=",,,," />
  <tile id="90" terrain=",,,," />
  <tile id="91" terrain=",,,," />
  <tile id="92" terrain=",,,," />
  <tile id="93" terrain=",,,," />
  <tile id="94" terrain=",,,," />
  <tile id="95" terrain=",,,," />
  <tile id="96" terrain=",,,," />
  <tile id="97" terrain=",,,," />
  <tile id="98" terrain=",,,," />
  <tile id="99" terrain=",,,," />
  <tile id="100" terrain=",,,," />
  <tile id="101" terrain=",,,," />
  <tile id="102" terrain=",,,," />
  <tile id="103" terrain=",,,," />
  <tile id="104" terrain=",,,," />
  <tile id="105" terrain=",,,," />
  <tile id="106" terrain=",,,," />
  <tile id="107" terrain=",,,," />
  <tile id="108" terrain=",,,," />
  <tile id="109" terrain=",,,," />
  <tile id="110" terrain=",,,," />
  <tile id="111" terrain=",,,," />
  <tile id="112" terrain=",,,," />
  <tile id="113" terrain=",,,," />
  <tile id="114" terrain=",,,," />
  <tile id="115" terrain=",,,," />
  <tile id="116" terrain=",,,," />
  <tile id="117" terrain=",,,," />
  <tile id="118" terrain=",,,," />
  <tile id="119" terrain=",,,," />
  <tile id="120" terrain=",,,," />
  <tile id="121" terrain=",,,," />
  <tile id="122" terrain=",,,," />
  <tile id="123" terrain=",,,," />
  <tile id="124" terrain=",,,," />
  <tile id="125" terrain=",,,," />
  <tile id="126" terrain=",,,," />
  <tile id="127" terrain=",,,," />
  <tile id="128" terrain=",,,," />
  <tile id="129" terrain=",,,," />
  <tile id="130" terrain=",,,," />
  <tile id="131" terrain=",,,," />
  <tile id="132" terrain=",,,," />
  <tile id="133" terrain=",,,," />
  <tile id="134" terrain=",,,," />
  <tile id="135" terrain=",,,," />
  <tile id="136" terrain=",,,," />
  <tile id="137" terrain=",,,," />
  <tile id="138" terrain=",,,," />
  <tile id="139" terrain=",,,," />
  <tile id="140" terrain=",,,," />
  <tile id="141" terrain=",,,," />
  <tile id="142" terrain=",,,," />
  <tile id="143" terrain=",,,," />
  <tile id="144" terrain=",,,," />
  <tile id="145" terrain=",,,," />
  <tile id="146" terrain=",,,," />
  <tile id="147" terrain=",,,," />
  <tile id="148" terrain=",,,," />
  <tile id="149" terrain=",,,," />
  <tile id="150" terrain=",,,," />
  <tile id="151" terrain=",,,," />
  <tile id="152" terrain=",,,," />
  <tile id="153" terrain=",,,," />
  <tile id="154" terrain=",,,," />
  <tile id="155" terrain=",,,," />
  <tile id="156" terrain=",,,," />
  <tile id="157" terrain=",,,," />
  <tile id="158" terrain=",,,," />
  <tile id="159" terrain=",,,," />
  <tile id="160" terrain=",,,," />
  <tile id="161" terrain=",,,," />
  <tile id="162" terrain=",,,," />
  <tile id="163" terrain=",,,," />
  <tile id="164" terrain=",,,," />
  <tile id="165" terrain=",,,," />
  <tile id="166" terrain=",,,," />
  <tile id="167" terrain=",,,," />
  <tile id="168" terrain=",,,," />
  <tile id="169" terrain=",,,," />
  <tile id="170" terrain=",,,," />
  <tile id="171" terrain=",,,," />
  <tile id="172" terrain=",,,," />
  <tile id="173" terrain=",,,," />
  <tile id="174" terrain=",,,," />
  <tile id="175" terrain=",,,," />
  <tile id="176" terrain=",,,," />
  <tile id="177" terrain=",,,," />
  <tile id="178" terrain=",,,," />
  <tile id="179" terrain=",,,," />
  <tile id="180" terrain=",,,," />
  <tile id="181" terrain=",,,," />
  <tile id="182" terrain=",,,," />
  <tile id="183" terrain=",,,," />
  <tile id="184" terrain=",,,," />
  <tile id="185" terrain=",,,," />
  <tile id="186" terrain=",,,," />
  <tile id="187" terrain=",,,," />
  <tile id="188" terrain=",,,," />
  <tile id="189" terrain=",,,," />
  <tile id="190" terrain=",,,," />
  <tile id="191" terrain=",,,," />
  <tile id="192" terrain=",,,," />
  <tile id="193" terrain=",,,," />
  <tile id="194" terrain=",,,," />
  <tile id="195" terrain=",,,," />
  <tile id="196" terrain=",,,," />
  <tile id="197" terrain=",,,," />
  <tile id="198" terrain=",,,," />
  <tile id="199" terrain=",,,," />
  <tile id="200" terrain=",,,," />
  <tile id="201" terrain=",,,," />
  <tile id="202" terrain=",,,," />
  <tile id="203" terrain=",,,," />
  <tile id="204" terrain=",,,," />
  <tile id="205" terrain=",,,," />
  <tile id="206" terrain=",,,," />
  <tile id="207" terrain=",,,," />
  <tile id="208" terrain=",,,," />
  <tile id="209" terrain=",,,," />
  <tile id="210" terrain=",,,," />
  <tile id="211" terrain=",,,," />
  <tile id="212" terrain=",,,," />
  <tile id="213" terrain=",,,," />
  <tile id="214" terrain=",,,," />
  <tile id="215" terrain=",,,," />
  <tile id="216" terrain=",,,," />
  <tile id="217" terrain=",,,," />
  <tile id="218" terrain=",,,," />
  <tile id="219" terrain=",,,," />
  <tile id="220" terrain=",,,," />
  <tile id="221" terrain=",,,," />
  <tile id="222" terrain=",,,," />
  <tile id="223" terrain=",,,," />
  <tile id="224" terrain=",,,," />
  <tile id="225" terrain=",,,," />
  <tile id="226" terrain=",,,," />
  <tile id="227" terrain=",,,," />
  <tile id="228" terrain=",,,," />
  <tile id="229" terrain=",,,," />
  <tile id="230" terrain=",,,," />
  <tile id="231" terrain=",,,," />
  <tile id="232" terrain=",,,," />
  <tile id="233" terrain=",,,," />
  <tile id="234" terrain=",,,," />
  <tile id="235" terrain=",,,," />
  <tile id="236" terrain=",,,," />
  <tile id="237" terrain=",,,," />
  <tile id="238" terrain=",,,," />
  <tile id="239" terrain=",,,," />
  <tile id="240" terrain=",,,," />
  <tile id="241" terrain=",,,," />
  <tile id="242" terrain=",,,," />
  <tile id="243" terrain=",,,," />
  <tile id="244" terrain=",,,," />
  <tile id="245" terrain=",,,," />
  <tile id="246" terrain=",,,," />
  <tile id="247" terrain=",,,," />
  <tile id="248" terrain=",,,," />
  <tile id="249" terrain=",,,," />
  <tile id="250" terrain=",,,," />
  <tile id="251" terrain=",,,," />
  <tile id="252" terrain=",,,," />
  <tile id="253" terrain=",,,," />
  <tile id="254" terrain=",,,," />
  <tile id="255" terrain=",,,," />
  </tileset>